name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]  # adjust branch as needed
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./Librarr
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/librarr:latest
#            user/app:latest # Docker Hub

      - name: Pull Docker image for artifact
        run: docker pull ghcr.io/${{ github.repository_owner }}/librarr:latest

      - name: Save Docker image as artifact
        run: docker save -o image.tar ghcr.io/${{ github.repository_owner }}/librarr:latest

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar